import type { Preset, VisualParameters } from "../types";

export const defaultParams: VisualParameters = {
  mode: "bloom",
  paletteId: "moonlight",
  density: 62,
  speed: 42,
  rotation: 36,
  symmetry: 8,
  trails: 72,
  glow: 68,
  bloom: 70,
  responsiveness: 72,
  background: 12,
  autoMotion: true,
  idle: 34,
  reducedMotion: false,
  quality: "auto",
  recipeSeed: 28471,
};

const preset = (
  id: string,
  name: string,
  changes: Partial<VisualParameters>,
  featured = false,
): Preset => ({
  id,
  name,
  builtIn: true,
  featured,
  params: { ...defaultParams, ...changes },
});

export const builtInPresets: Preset[] = [
  preset(
    "moonlit-bloom",
    "Moonlit Bloom",
    {
      mode: "bloom",
      paletteId: "moonlight",
      symmetry: 9,
      density: 54,
      speed: 29,
      rotation: 27,
      glow: 74,
      trails: 81,
      bloom: 72,
      responsiveness: 79,
      background: 7,
      idle: 28,
      recipeSeed: 28471,
    },
    true,
  ),
  preset("aurora-garden", "Aurora Garden", {
    mode: "bloom",
    paletteId: "aurora",
    density: 78,
    speed: 47,
    rotation: 57,
    trails: 75,
    glow: 84,
    bloom: 91,
    responsiveness: 88,
    symmetry: 7,
    background: 13,
    idle: 36,
    recipeSeed: 64820,
  }),
  preset("deep-ocean", "Deep Ocean", {
    mode: "ribbons",
    paletteId: "ocean",
    density: 47,
    speed: 24,
    rotation: 18,
    symmetry: 5,
    trails: 82,
    glow: 54,
    bloom: 43,
    responsiveness: 74,
    background: 6,
    idle: 31,
    autoMotion: true,
  }),
  preset(
    "cosmic-choir",
    "Cosmic Choir",
    {
      mode: "orbit",
      paletteId: "violet",
      density: 59,
      speed: 33,
      rotation: 57,
      trails: 78,
      glow: 79,
      bloom: 62,
      responsiveness: 82,
      symmetry: 6,
      background: 6,
      recipeSeed: 73018,
    },
    true,
  ),
  preset("ember-spiral", "Ember Spiral", {
    mode: "orbit",
    paletteId: "embers",
    density: 72,
    speed: 63,
    rotation: 81,
    symmetry: 5,
    trails: 85,
    glow: 82,
    bloom: 71,
    responsiveness: 91,
    background: 10,
    idle: 24,
    recipeSeed: 10593,
  }),
  preset(
    "glass-cathedral",
    "Glass Cathedral",
    {
      mode: "ribbons",
      paletteId: "silver",
      density: 63,
      symmetry: 11,
      speed: 31,
      rotation: 43,
      trails: 78,
      glow: 52,
      bloom: 42,
      responsiveness: 86,
      background: 5,
      idle: 25,
      recipeSeed: 35791,
    },
    true,
  ),
  preset(
    "midnight-constellation",
    "Midnight Constellation",
    {
      mode: "constellation",
      paletteId: "moonlight",
      density: 49,
      speed: 17,
      rotation: 21,
      symmetry: 5,
      glow: 78,
      trails: 68,
      bloom: 55,
      responsiveness: 81,
      background: 5,
      idle: 34,
      recipeSeed: 84017,
    },
    true,
  ),
  preset("celestial-cartography", "Celestial Cartography", {
    mode: "constellation",
    paletteId: "gold",
    density: 67,
    speed: 38,
    rotation: 49,
    symmetry: 8,
    trails: 76,
    glow: 87,
    bloom: 72,
    responsiveness: 89,
    background: 12,
    idle: 43,
    recipeSeed: 29764,
  }),
  preset("dreaming-jellyfish", "Dreaming Jellyfish", {
    mode: "jellyfish",
    paletteId: "violet",
    density: 67,
    speed: 26,
    rotation: 24,
    trails: 94,
    glow: 91,
    bloom: 94,
    responsiveness: 76,
    symmetry: 5,
    background: 12,
    idle: 51,
    recipeSeed: 50422,
  }),
  preset(
    "abyssal-lanterns",
    "Abyssal Lanterns",
    {
      mode: "jellyfish",
      paletteId: "ocean",
      density: 45,
      speed: 14,
      rotation: 12,
      trails: 94,
      glow: 83,
      bloom: 84,
      responsiveness: 70,
      background: 6,
      idle: 39,
      recipeSeed: 73104,
    },
    true,
  ),
  preset(
    "temple-resonance",
    "Temple Resonance",
    {
      mode: "geometry",
      paletteId: "gold",
      density: 58,
      speed: 19,
      rotation: 29,
      symmetry: 10,
      trails: 65,
      glow: 66,
      background: 5,
      responsiveness: 86,
      idle: 21,
      recipeSeed: 41027,
    },
    true,
  ),
  preset("aurora-shrine", "Aurora Shrine", {
    mode: "geometry",
    paletteId: "aurora",
    density: 68,
    speed: 27,
    rotation: 46,
    symmetry: 8,
    trails: 72,
    glow: 81,
    bloom: 77,
    responsiveness: 91,
    background: 10,
    idle: 29,
    recipeSeed: 88216,
  }),
  preset(
    "velvet-cosmos",
    "Velvet Cosmos",
    {
      mode: "nebula",
      paletteId: "violet",
      density: 55,
      speed: 19,
      rotation: 28,
      symmetry: 5,
      trails: 92,
      glow: 78,
      bloom: 82,
      responsiveness: 76,
      background: 8,
      idle: 42,
      recipeSeed: 15903,
    },
    true,
  ),
  preset("solar-bloom", "Solar Bloom", {
    mode: "nebula",
    paletteId: "sunset",
    density: 76,
    speed: 39,
    rotation: 54,
    symmetry: 7,
    trails: 88,
    glow: 91,
    bloom: 94,
    responsiveness: 91,
    background: 15,
    idle: 35,
    recipeSeed: 55261,
  }),
  preset(
    "moss-cathedral",
    "Moss Cathedral",
    {
      mode: "forest",
      paletteId: "forest",
      density: 58,
      speed: 16,
      trails: 76,
      glow: 62,
      bloom: 78,
      background: 9,
      responsiveness: 72,
      idle: 37,
      recipeSeed: 62419,
    },
    true,
  ),
  preset("spores-at-midnight", "Spores at Midnight", {
    mode: "forest",
    paletteId: "neon",
    density: 66,
    speed: 34,
    rotation: 29,
    symmetry: 6,
    trails: 84,
    glow: 74,
    bloom: 91,
    responsiveness: 88,
    background: 7,
    idle: 45,
    recipeSeed: 90372,
  }),
  preset(
    "chrome-tide",
    "Chrome Tide",
    {
      mode: "metal",
      paletteId: "silver",
      density: 43,
      speed: 37,
      rotation: 32,
      symmetry: 5,
      trails: 68,
      glow: 49,
      bloom: 64,
      responsiveness: 86,
      background: 4,
      idle: 20,
      recipeSeed: 30744,
    },
    true,
  ),
  preset("mercury-cathedral", "Mercury Cathedral", {
    mode: "metal",
    paletteId: "neon",
    density: 61,
    speed: 58,
    rotation: 63,
    symmetry: 7,
    trails: 81,
    glow: 68,
    bloom: 82,
    responsiveness: 95,
    background: 9,
    idle: 27,
    recipeSeed: 68031,
  }),
  preset(
    "event-horizon",
    "Event Horizon",
    {
      mode: "portal",
      paletteId: "violet",
      density: 68,
      speed: 49,
      rotation: 73,
      symmetry: 7,
      trails: 87,
      glow: 85,
      bloom: 91,
      responsiveness: 93,
      background: 5,
      idle: 31,
      recipeSeed: 77138,
    },
    true,
  ),
  preset("resonant-gate", "Resonant Gate", {
    mode: "portal",
    paletteId: "gold",
    density: 49,
    speed: 25,
    rotation: 47,
    symmetry: 9,
    trails: 77,
    glow: 72,
    bloom: 79,
    responsiveness: 84,
    background: 4,
    idle: 23,
    recipeSeed: 24580,
  }),
];

const STORAGE_KEY = "music-bloom-custom-presets-v1";

export function loadCustomPresets(): Preset[] {
  try {
    const stored = JSON.parse(
      localStorage.getItem(STORAGE_KEY) ?? "[]",
    ) as unknown;
    if (!Array.isArray(stored)) return [];
    return stored.filter(isPreset).map((item) => ({
      ...item,
      builtIn: false,
      params: { ...defaultParams, ...item.params },
    }));
  } catch {
    return [];
  }
}

export function saveCustomPresets(presets: Preset[]): void {
  localStorage.setItem(
    STORAGE_KEY,
    JSON.stringify(presets.filter((item) => !item.builtIn)),
  );
}

function isPreset(value: unknown): value is Preset {
  if (!value || typeof value !== "object") return false;
  const item = value as Partial<Preset>;
  return (
    typeof item.id === "string" &&
    typeof item.name === "string" &&
    !!item.params &&
    typeof item.params === "object"
  );
}
